name: "Read QPM info"
description: "Reads the qpm.json info into outputs for you to use in your github actions"
author: "RedBrumbler"

inputs:
  package_path:
    required: false
    description: "Path to the package you want to read"
    default: "qpm.json"
  shared:
    required: false
    description: "Whether the package path provided is a shared json instead"
    default: 'false'

outputs:
  name:
    description: "package name"
  id:
    description: "package id"
  version:
    description: "package id"
  url:
    description: "package url"

runs:
  using: node20
  main: dist/index.js
